---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
pages:
- projects/molecular-gastronomy.md
- projects/u-x-u-i-re-design-app-peekaboo-moments.md
- projects/u-x-u-i-re-design-website-https-its.taiwanjobs.gov.tw.md
- projects/°-jupiter-calendar.md
