---
label: Project
hide_body: false
fields:
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
pages:
- projects/molecular-gastronomy.md
- projects/°-jupiter-calendar.md
